services:
  db:
    image: postgres:16
    container_name: fintrack-db
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5433:5432"
    volumes:
      - fintrack_pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: fintrack-app
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  fintrack_pgdata: