ktor:
  deployment:
    port: 8080
  application:
    modules:
      - org.example.ApplicationKt.module

db:
  driver: "org.h2.Driver"
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"
  user: "sa"
  password: ""

jwt:
  issuer: "http://0.0.0.0:8080/"
  audience: "events-api"
  realm: "events-api"
  secret: "change-me"
  expiresMs: 3600000